# Generated by Django 5.1.3 on 2024-12-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_managers_remove_user_username_user_rank_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('image', models.ImageField(upload_to='books/')),
            ],
        ),
    ]
