# Generated by Django 5.1.3 on 2024-12-04 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_unit_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='name',
        ),
    ]
