# Generated by Django 5.1.3 on 2024-12-04 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_unit_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uzbek', models.CharField(max_length=255)),
                ('english', models.CharField(max_length=255)),
                ('audio', models.FileField(upload_to='vocabulary_audio/')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabularies', to='user.unit')),
            ],
        ),
    ]
