# Generated by Django 5.1.3 on 2024-12-09 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_unit_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='test_section',
        ),
        migrations.DeleteModel(
            name='TestSection',
        ),
    ]
