# Generated by Django 5.1.3 on 2024-12-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_remove_test_test_section_delete_testsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='theme',
            field=models.CharField(default=1, max_length=350),
            preserve_default=False,
        ),
    ]
